"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Header from "@/components/ui/header";
import { livePages } from "@/app/live/live-slugs";
import { templates } from "@/app/templates/template-catalog";

type FixTask = {
  id: string;
  text: string;
  createdAt: string;
  updatedAt: string;
  autoGenerated: boolean;
};

type ChangeRecord = {
  id: string;
  appSlug: string;
  action: string;
  detail: string;
  at: string;
};

type AppMaintenance = {
  slug: string;
  title: string;
  technicalSummary: string;
  plainSummary: string;
  status: "unknown" | "functional" | "not-fixed";
  lastVerifiedAt: string | null;
  fixTodo: FixTask[];
  fixDone: FixTask[];
  records: ChangeRecord[];
};

const STATE_KEY = "isla_maintenance_state_v1";
const AUTH_KEY = "isla_maintenance_auth_v1";
const DEFAULT_ADMIN_PIN = "isla-admin";

function uid(prefix: string) {
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}

function stamp() {
  return new Date().toLocaleString();
}

function buildTechnicalSummary(title: string, desc: string) {
  return `${title} is implemented as a Next.js + TypeScript web app with route-level live demo access, state-driven user flows, and event logging for key actions. It currently supports: ${desc}`;
}

function buildPlainSummary(title: string, desc: string) {
  return `${title} is a practical app your team can use to run day-to-day work. It helps users complete real tasks instead of just viewing a mockup. Main capabilities include: ${desc}`;
}

function createInitialApps(): AppMaintenance[] {
  const liveTemplateSet = new Set(livePages);
  return templates
    .filter((tpl) => liveTemplateSet.has(tpl.slug as (typeof livePages)[number]))
    .map((tpl) => ({
      slug: tpl.slug,
      title: tpl.title,
      technicalSummary: buildTechnicalSummary(tpl.title, tpl.desc),
      plainSummary: buildPlainSummary(tpl.title, tpl.desc),
      status: "unknown",
      lastVerifiedAt: null,
      fixTodo: [],
      fixDone: [],
      records: [],
    }));
}

export default function MaintenanceAdminPage() {
  const [isAuthed, setIsAuthed] = useState(false);
  const [pinInput, setPinInput] = useState("");
  const [pinError, setPinError] = useState("");

  const [apps, setApps] = useState<AppMaintenance[]>([]);
  const [selectedSlug, setSelectedSlug] = useState<string>("");
  const [newFixText, setNewFixText] = useState("");
  const [autoVerify, setAutoVerify] = useState(true);

  useEffect(() => {
    const authed = window.sessionStorage.getItem(AUTH_KEY) === "1";
    setIsAuthed(authed);

    const fallback = createInitialApps();
    const raw = window.localStorage.getItem(STATE_KEY);
    if (!raw) {
      setApps(fallback);
      setSelectedSlug(fallback[0]?.slug ?? "");
      return;
    }

    try {
      const saved = JSON.parse(raw) as AppMaintenance[];
      const map = new Map(saved.map((app) => [app.slug, app]));
      const merged = fallback.map((base) => map.get(base.slug) ?? base);
      setApps(merged);
      setSelectedSlug(merged[0]?.slug ?? "");
    } catch {
      setApps(fallback);
      setSelectedSlug(fallback[0]?.slug ?? "");
    }
  }, []);

  useEffect(() => {
    if (!apps.length) return;
    window.localStorage.setItem(STATE_KEY, JSON.stringify(apps));
  }, [apps]);

  const selectedApp = useMemo(
    () => apps.find((app) => app.slug === selectedSlug) ?? apps[0],
    [apps, selectedSlug],
  );

  const addRecord = (slug: string, action: string, detail: string) => {
    setApps((prev) =>
      prev.map((app) =>
        app.slug === slug
          ? {
              ...app,
              records: [{ id: uid("rec"), appSlug: slug, action, detail, at: stamp() }, ...app.records],
            }
          : app,
      ),
    );
  };

  const updateSelectedInfo = (field: "technicalSummary" | "plainSummary", value: string) => {
    if (!selectedApp) return;
    setApps((prev) => prev.map((app) => (app.slug === selectedApp.slug ? { ...app, [field]: value } : app)));
  };

  const saveSelectedInfo = () => {
    if (!selectedApp) return;
    addRecord(selectedApp.slug, "INFO_UPDATED", "App summaries updated by admin.");
  };

  const addFixTodo = () => {
    if (!selectedApp || !newFixText.trim()) return;
    const now = stamp();
    const task: FixTask = {
      id: uid("fix"),
      text: newFixText.trim(),
      createdAt: now,
      updatedAt: now,
      autoGenerated: false,
    };
    setApps((prev) =>
      prev.map((app) => (app.slug === selectedApp.slug ? { ...app, fixTodo: [task, ...app.fixTodo] } : app)),
    );
    addRecord(selectedApp.slug, "FIX_ADDED", `Todo added: ${task.text}`);
    setNewFixText("");
  };

  const moveToDone = (taskId: string) => {
    if (!selectedApp) return;
    const found = selectedApp.fixTodo.find((t) => t.id === taskId);
    if (!found) return;
    const now = stamp();
    const moved = { ...found, updatedAt: now };
    setApps((prev) =>
      prev.map((app) =>
        app.slug === selectedApp.slug
          ? {
              ...app,
              status: app.fixTodo.length <= 1 ? "functional" : app.status,
              fixTodo: app.fixTodo.filter((t) => t.id !== taskId),
              fixDone: [moved, ...app.fixDone],
            }
          : app,
      ),
    );
    addRecord(selectedApp.slug, "FIX_DONE", `Task moved to done: ${moved.text}`);
  };

  const moveToTodo = (taskId: string) => {
    if (!selectedApp) return;
    const found = selectedApp.fixDone.find((t) => t.id === taskId);
    if (!found) return;
    const now = stamp();
    const moved = { ...found, updatedAt: now };
    setApps((prev) =>
      prev.map((app) =>
        app.slug === selectedApp.slug
          ? {
              ...app,
              status: "not-fixed",
              fixDone: app.fixDone.filter((t) => t.id !== taskId),
              fixTodo: [moved, ...app.fixTodo],
            }
          : app,
      ),
    );
    addRecord(selectedApp.slug, "FIX_REOPENED", `Task reopened: ${moved.text}`);
  };

  const runVerificationForApp = async (slug: string) => {
    const now = stamp();
    try {
      const res = await fetch(`/live/${slug}`, { method: "GET", cache: "no-store" });
      const isOk = res.ok;
      const failText = "Auto functional check failed. Review runtime flow and page rendering.";
      setApps((prev) =>
        prev.map((app) => {
          if (app.slug !== slug) return app;

          if (isOk) {
            const autoFailTodo = app.fixTodo.find((t) => t.autoGenerated && t.text === failText);
            if (!autoFailTodo) {
              return {
                ...app,
                status: app.fixTodo.length ? "not-fixed" : "functional",
                lastVerifiedAt: now,
              };
            }
            const closed = { ...autoFailTodo, updatedAt: now };
            return {
              ...app,
              status: app.fixTodo.length <= 1 ? "functional" : "not-fixed",
              lastVerifiedAt: now,
              fixTodo: app.fixTodo.filter((t) => t.id !== autoFailTodo.id),
              fixDone: [closed, ...app.fixDone],
              records: [
                {
                  id: uid("rec"),
                  appSlug: slug,
                  action: "AUTO_FIX_MOVED_TO_DONE",
                  detail: `Auto-check recovered. Task moved to done: ${closed.text}`,
                  at: now,
                },
                ...app.records,
              ],
            };
          }

          const hasAutoFail = app.fixTodo.some((t) => t.autoGenerated && t.text === failText);
          if (hasAutoFail) {
            return { ...app, status: "not-fixed", lastVerifiedAt: now };
          }
          const failTask: FixTask = {
            id: uid("fix"),
            text: failText,
            createdAt: now,
            updatedAt: now,
            autoGenerated: true,
          };
          return {
            ...app,
            status: "not-fixed",
            lastVerifiedAt: now,
            fixTodo: [failTask, ...app.fixTodo],
            records: [
              {
                id: uid("rec"),
                appSlug: slug,
                action: "AUTO_FIX_ADDED",
                detail: `Auto-check failed and created todo: ${failText}`,
                at: now,
              },
              ...app.records,
            ],
          };
        }),
      );
      addRecord(slug, "VERIFY_RUN", isOk ? "Functional check passed." : "Functional check failed.");
    } catch {
      const failText = "Auto functional check failed. Network or route error.";
      setApps((prev) =>
        prev.map((app) => {
          if (app.slug !== slug) return app;
          const hasTask = app.fixTodo.some((t) => t.autoGenerated && t.text === failText);
          if (hasTask) return { ...app, status: "not-fixed", lastVerifiedAt: now };
          return {
            ...app,
            status: "not-fixed",
            lastVerifiedAt: now,
            fixTodo: [
              {
                id: uid("fix"),
                text: failText,
                createdAt: now,
                updatedAt: now,
                autoGenerated: true,
              },
              ...app.fixTodo,
            ],
          };
        }),
      );
      addRecord(slug, "VERIFY_RUN", "Functional check failed due to request error.");
    }
  };

  const runVerificationAll = async () => {
    for (const app of apps) {
      // Serial verification keeps writes ordered and easier to audit in record logs.
      // eslint-disable-next-line no-await-in-loop
      await runVerificationForApp(app.slug);
    }
  };

  useEffect(() => {
    if (!isAuthed || !autoVerify || !apps.length) return;
    const id = window.setInterval(() => {
      runVerificationAll();
    }, 60000);
    return () => window.clearInterval(id);
  }, [isAuthed, autoVerify, apps.length]);

  const login = () => {
    const pin = (process.env.NEXT_PUBLIC_ISLA_ADMIN_PIN || DEFAULT_ADMIN_PIN).trim();
    if (pinInput.trim() !== pin) {
      setPinError("Invalid admin PIN.");
      return;
    }
    setPinError("");
    setIsAuthed(true);
    window.sessionStorage.setItem(AUTH_KEY, "1");
  };

  const logout = () => {
    setIsAuthed(false);
    window.sessionStorage.removeItem(AUTH_KEY);
  };

  const statusClass =
    selectedApp?.status === "functional"
      ? "bg-emerald-600/20 text-emerald-300"
      : selectedApp?.status === "not-fixed"
        ? "bg-amber-600/20 text-amber-300"
        : "bg-slate-700/50 text-slate-300";

  return (
    <>
      <Header />
      <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6">
        <div className="rounded-2xl border border-gray-800 bg-gray-900/60 p-6">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h1 className="text-2xl font-semibold text-gray-100">Admin Update & Maintenance</h1>
            <Link
              href="/templates"
              className="rounded-lg border border-gray-700 bg-gray-800 px-3 py-2 text-sm font-medium text-gray-100 hover:bg-gray-700"
            >
              Go to Demo Gallery
            </Link>
          </div>
          <p className="mt-2 text-sm text-indigo-100/70">
            Admin-only workspace for app info updates, fix tracking, continuous functional checks, and timestamped record logs.
          </p>
        </div>

        {!isAuthed ? (
          <div className="mt-6 max-w-md rounded-2xl border border-gray-800 bg-gray-900/60 p-6">
            <h2 className="text-lg font-semibold text-gray-100">Admin Access</h2>
            <p className="mt-2 text-sm text-indigo-100/70">Enter admin PIN to open maintenance controls.</p>
            <input
              type="password"
              value={pinInput}
              onChange={(e) => setPinInput(e.target.value)}
              className="mt-4 w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-gray-100"
              placeholder="Admin PIN"
            />
            {pinError && <p className="mt-2 text-sm text-red-300">{pinError}</p>}
            <button type="button" onClick={login} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-500">
              Unlock
            </button>
          </div>
        ) : (
          <div className="mt-6 grid gap-6 lg:grid-cols-[280px_1fr]">
            <aside className="rounded-2xl border border-gray-800 bg-gray-900/60 p-4">
              <div className="mb-3 flex items-center justify-between">
                <h2 className="text-base font-semibold text-gray-100">Apps ({apps.length})</h2>
                <button type="button" onClick={logout} className="text-xs text-indigo-300 hover:text-indigo-200">
                  Log out
                </button>
              </div>
              <div className="space-y-2">
                {apps.map((app) => (
                  <button
                    key={app.slug}
                    type="button"
                    onClick={() => setSelectedSlug(app.slug)}
                    className={`w-full rounded-lg border px-3 py-2 text-left ${selectedSlug === app.slug ? "border-indigo-500 bg-indigo-500/10 text-white" : "border-gray-700 bg-gray-950 text-gray-300"}`}
                  >
                    <p className="text-sm font-medium">{app.title}</p>
                    <p className="text-xs text-indigo-100/65">/{app.slug}</p>
                  </button>
                ))}
              </div>
            </aside>

            {selectedApp && (
              <main className="space-y-6">
                <div className="rounded-2xl border border-gray-800 bg-gray-900/60 p-5">
                  <div className="flex flex-wrap items-center gap-3">
                    <h2 className="text-xl font-semibold text-gray-100">{selectedApp.title}</h2>
                    <span className={`rounded-full px-2.5 py-1 text-xs ${statusClass}`}>{selectedApp.status}</span>
                    <span className="rounded-full bg-gray-800 px-2.5 py-1 text-xs text-indigo-100/70">
                      Last verify: {selectedApp.lastVerifiedAt ?? "never"}
                    </span>
                  </div>
                  <div className="mt-4 flex flex-wrap gap-3">
                    <button type="button" onClick={() => runVerificationForApp(selectedApp.slug)} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-500">
                      Verify this app
                    </button>
                    <button type="button" onClick={runVerificationAll} className="rounded-lg border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-gray-100 hover:bg-gray-700">
                      Verify all apps
                    </button>
                    <label className="inline-flex items-center gap-2 rounded-lg border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-gray-100">
                      <input type="checkbox" checked={autoVerify} onChange={(e) => setAutoVerify(e.target.checked)} />
                      Continuous verification (60s)
                    </label>
                  </div>
                </div>

                <div className="grid gap-6 xl:grid-cols-2">
                  <section className="rounded-2xl border border-gray-800 bg-gray-900/60 p-5">
                    <h3 className="text-base font-semibold text-gray-100">Technical Summary</h3>
                    <textarea
                      value={selectedApp.technicalSummary}
                      onChange={(e) => updateSelectedInfo("technicalSummary", e.target.value)}
                      className="mt-3 h-36 w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-gray-100"
                    />
                  </section>
                  <section className="rounded-2xl border border-gray-800 bg-gray-900/60 p-5">
                    <h3 className="text-base font-semibold text-gray-100">Plain Reader Summary</h3>
                    <textarea
                      value={selectedApp.plainSummary}
                      onChange={(e) => updateSelectedInfo("plainSummary", e.target.value)}
                      className="mt-3 h-36 w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-gray-100"
                    />
                  </section>
                </div>

                <button type="button" onClick={saveSelectedInfo} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-500">
                  Save App Information
                </button>

                <div className="grid gap-6 xl:grid-cols-2">
                  <section className="rounded-2xl border border-gray-800 bg-gray-900/60 p-5">
                    <h3 className="text-base font-semibold text-gray-100">Fixings To Do</h3>
                    <div className="mt-3 flex gap-2">
                      <input
                        value={newFixText}
                        onChange={(e) => setNewFixText(e.target.value)}
                        placeholder="Add a fix task"
                        className="w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-gray-100"
                      />
                      <button type="button" onClick={addFixTodo} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white hover:bg-indigo-500">
                        Add
                      </button>
                    </div>
                    <div className="mt-4 space-y-2">
                      {selectedApp.fixTodo.length === 0 ? (
                        <p className="text-sm text-indigo-100/60">No pending fix tasks.</p>
                      ) : (
                        selectedApp.fixTodo.map((task) => (
                          <label key={task.id} className="flex items-start gap-2 rounded-lg border border-gray-700 bg-gray-950 p-3">
                            <input type="checkbox" onChange={() => moveToDone(task.id)} />
                            <div className="text-sm">
                              <p className="text-gray-100">{task.text}</p>
                              <p className="text-xs text-indigo-100/60">
                                Created: {task.createdAt} | Updated: {task.updatedAt} {task.autoGenerated ? "| auto" : ""}
                              </p>
                            </div>
                          </label>
                        ))
                      )}
                    </div>
                  </section>

                  <section className="rounded-2xl border border-gray-800 bg-gray-900/60 p-5">
                    <h3 className="text-base font-semibold text-gray-100">Fixings Already Done</h3>
                    <div className="mt-4 space-y-2">
                      {selectedApp.fixDone.length === 0 ? (
                        <p className="text-sm text-indigo-100/60">No completed fix tasks yet.</p>
                      ) : (
                        selectedApp.fixDone.map((task) => (
                          <label key={task.id} className="flex items-start gap-2 rounded-lg border border-gray-700 bg-gray-950 p-3">
                            <input type="checkbox" checked onChange={() => moveToTodo(task.id)} />
                            <div className="text-sm">
                              <p className="text-gray-100">{task.text}</p>
                              <p className="text-xs text-indigo-100/60">
                                Created: {task.createdAt} | Updated: {task.updatedAt} {task.autoGenerated ? "| auto" : ""}
                              </p>
                            </div>
                          </label>
                        ))
                      )}
                    </div>
                  </section>
                </div>

                <section className="rounded-2xl border border-gray-800 bg-gray-900/60 p-5">
                  <h3 className="text-base font-semibold text-gray-100">Record Section (Timestamped)</h3>
                  <p className="mt-1 text-sm text-indigo-100/70">
                    Every admin transaction in this panel is logged with date and time.
                  </p>
                  <div className="mt-4 max-h-80 space-y-2 overflow-auto">
                    {selectedApp.records.length === 0 ? (
                      <p className="text-sm text-indigo-100/60">No records yet for this app.</p>
                    ) : (
                      selectedApp.records.map((rec) => (
                        <div key={rec.id} className="rounded-lg border border-gray-700 bg-gray-950 p-3 text-sm">
                          <p className="font-medium text-gray-100">{rec.action}</p>
                          <p className="text-indigo-100/75">{rec.detail}</p>
                          <p className="text-xs text-indigo-100/55">{rec.at}</p>
                        </div>
                      ))
                    )}
                  </div>
                </section>
              </main>
            )}
          </div>
        )}
      </section>
    </>
  );
}
