import type { StaticImageData } from "next/image";
import heroImage01 from "@/public/images/hero-image-01.jpg";
import workflow01 from "@/public/images/workflow-01.png";
import workflow02 from "@/public/images/workflow-02.png";
import workflow03 from "@/public/images/workflow-03.png";
import carousel01 from "@/public/images/carousel-01.png";
import carousel02 from "@/public/images/carousel-02.png";
import carousel03 from "@/public/images/carousel-03.png";
import featuresImage from "@/public/images/features.png";
import worldmapImage from "@/public/images/worldmap.png";
import teamMosaic01 from "@/public/images/team-mosaic-01.jpg";
import teamMosaic02 from "@/public/images/team-mosaic-02.jpg";
import bookflowThumb from "@/public/templates/bookflow-thumb.png";
import medtrackThumb from "@/public/templates/medtrack-thumb.png";
import fitcoachThumb from "@/public/templates/fitcoach-thumb.png";
import restaurantThumb from "@/public/templates/restaurant-thumb.png";
import postThumb01 from "@/public/images/post-thumb-01.jpg";
import postThumb02 from "@/public/images/post-thumb-02.jpg";
import postThumb04 from "@/public/images/post-thumb-04.jpg";
import postThumb07 from "@/public/images/post-thumb-07.jpg";
import postThumb10 from "@/public/images/post-thumb-10.jpg";
import postThumb11 from "@/public/images/post-thumb-11.jpg";
import postThumb13 from "@/public/images/post-thumb-13.jpg";
import postThumb15 from "@/public/images/post-thumb-15.jpg";

export type TemplateDefinition = {
  slug: string;
  title: string;
  titleEs: string;
  tags: string[];
  desc: string;
  descEs: string;
  thumb: StaticImageData;
  hero: StaticImageData;
};

const thumbs = {heroImage01,workflow01,workflow02,workflow03,carousel01,carousel02,carousel03,featuresImage,worldmapImage,teamMosaic01,teamMosaic02,postThumb01,postThumb02,postThumb04,postThumb07,postThumb10,postThumb11,postThumb13,postThumb15};

export const templates: TemplateDefinition[] = [
{
  slug: "bookflow",
  title: "BookFlow (Service Booking)",
  titleEs: "BookFlow (Service Booking)",
  tags: ["Bookings", "POS-ready", "Client-ready"],
  desc: "Service bookings with POS handoff, receipts, and quick brand swap. Ideal for salons, clinics, wellness.",
  descEs: "Service bookings with POS handoff, receipts, and quick brand swap. Ideal for salons, clinics, wellness.",
  thumb: bookflowThumb,
  hero: bookflowThumb,
},
{
  slug: "medtrack",
  title: "MedTrack (Medication Manager)",
  titleEs: "MedTrack (Medication Manager)",
  tags: ["Health", "Reminders", "Tracking"],
  desc: "Medication schedules, refill prompts, and adherence logs. Customizable colors and pill schedules per persona.",
  descEs: "Medication schedules, refill prompts, and adherence logs. Customizable colors and pill schedules per persona.",
  thumb: medtrackThumb,
  hero: medtrackThumb,
},
{
  slug: "fitcoach",
  title: "FitCoach (Wellness Program)",
  titleEs: "FitCoach (Wellness Program)",
  tags: ["Fitness", "Coaching", "Subscriptions"],
  desc: "Coaching plans with weekly check-ins, progress cards, and recurring billing. Swap brand palette in minutes.",
  descEs: "Coaching plans with weekly check-ins, progress cards, and recurring billing. Swap brand palette in minutes.",
  thumb: fitcoachThumb,
  hero: fitcoachThumb,
},
{
  slug: "restaurant",
  title: "TableReady (Restaurant)",
  titleEs: "TableReady (Restaurant)",
  tags: ["Bookings", "Menus", "Payments"],
  desc: "Reservations, QR menus, and deposits. Replace hero with your dining shot; auto-adapts typography to brand.",
  descEs: "Reservations, QR menus, and deposits. Replace hero with your dining shot; auto-adapts typography to brand.",
  thumb: restaurantThumb,
  hero: restaurantThumb,
},
{
  slug: "spa",
  title: "CalmSpa (Salon & Spa)",
  titleEs: "CalmSpa (Salon & Spa)",
  tags: ["Wellness", "Bookings", "Gift Cards"],
  desc: "Service menu + upsells + gift cards. Swap accent color and CTA copy for promos in under a minute.",
  descEs: "Service menu + upsells + gift cards. Swap accent color and CTA copy for promos in under a minute.",
  thumb: carousel01,
  hero: carousel01,
},
{
  slug: "clinic",
  title: "CareLine (Clinic)",
  titleEs: "CareLine (Clinic)",
  tags: ["Healthcare", "Intake", "Scheduling"],
  desc: "Patient intake with HIPAA-friendly forms, appointment slots, and SMS reminders. Swap hero image and logo fast.",
  descEs: "Patient intake with HIPAA-friendly forms, appointment slots, and SMS reminders. Swap hero image and logo fast.",
  thumb: carousel02,
  hero: carousel02,
},
{
  slug: "dental",
  title: "SmileSet (Dental)",
  titleEs: "SmileSet (Dental)",
  tags: ["Dental", "Bookings", "Financing"],
  desc: "Treatment highlights, financing CTAs, and hygienist scheduling. Update accent to match your practice colors.",
  descEs: "Treatment highlights, financing CTAs, and hygienist scheduling. Update accent to match your practice colors.",
  thumb: carousel03,
  hero: carousel03,
},
{
  slug: "law",
  title: "Briefly (Law Firm)",
  titleEs: "Briefly (Law Firm)",
  tags: ["Professional", "Leads", "Appointments"],
  desc: "Case types, attorney bios, and consult booking. Swap sections for practice areas; keep intake flow intact.",
  descEs: "Case types, attorney bios, and consult booking. Swap sections for practice areas; keep intake flow intact.",
  thumb: featuresImage,
  hero: featuresImage,
},
{
  slug: "real-estate",
  title: "EstateGo (Real Estate)",
  titleEs: "EstateGo (Real Estate)",
  tags: ["Listings", "Leads", "Tours"],
  desc: "Property highlights, map embeds, and tour booking. Swap cover photo per campaign; lead form stays wired.",
  descEs: "Property highlights, map embeds, and tour booking. Swap cover photo per campaign; lead form stays wired.",
  thumb: worldmapImage,
  hero: worldmapImage,
},
{
  slug: "coaching",
  title: "Clarity Coach",
  titleEs: "Clarity Coach",
  tags: ["Coaching", "Funnels", "Payments"],
  desc: "Program overview, testimonials, and session booking. Swap hero and colors to match your personal brand.",
  descEs: "Program overview, testimonials, and session booking. Swap hero and colors to match your personal brand.",
  thumb: teamMosaic01,
  hero: teamMosaic01,
},
{
  slug: "saas",
  title: "LaunchPad (SaaS)",
  titleEs: "LaunchPad (SaaS)",
  tags: ["SaaS", "Product", "Waitlist"],
  desc: "Feature blocks, pricing, and waitlist. Toggle between dark/light; swap icon set and primary CTA text.",
  descEs: "Feature blocks, pricing, and waitlist. Toggle between dark/light; swap icon set and primary CTA text.",
  thumb: teamMosaic02,
  hero: teamMosaic02,
},
{
  slug: "analytics",
  title: "PulseDash (Analytics)",
  titleEs: "PulseDash (Analytics)",
  tags: ["Dashboards", "B2B", "Leads"],
  desc: "Metric highlights, integration logos, and demo booking. Swap screenshots; keep CTA row pinned.",
  descEs: "Metric highlights, integration logos, and demo booking. Swap screenshots; keep CTA row pinned.",
  thumb: postThumb01,
  hero: postThumb01,
},
{
  slug: "startup",
  title: "Elevate (Startup)",
  titleEs: "Elevate (Startup)",
  tags: ["Pitch", "Investors", "Team"],
  desc: "Story-driven hero, traction stats, team grid. Replace imagery and brand color in seconds.",
  descEs: "Story-driven hero, traction stats, team grid. Replace imagery and brand color in seconds.",
  thumb: postThumb02,
  hero: postThumb02,
},
{
  slug: "portfolio",
  title: "FolioPrime",
  titleEs: "FolioPrime",
  tags: ["Portfolio", "Freelance", "Contact"],
  desc: "Case studies with gallery, services, and contact form. Swap thumbnails and accent color easily.",
  descEs: "Case studies with gallery, services, and contact form. Swap thumbnails and accent color easily.",
  thumb: postThumb04,
  hero: postThumb04,
},
{
  slug: "agency",
  title: "North Studio (Agency)",
  titleEs: "North Studio (Agency)",
  tags: ["Agency", "Services", "Leads"],
  desc: "Service menu, results carousel, and booking CTA. Swap background glow and logos fast.",
  descEs: "Service menu, results carousel, and booking CTA. Swap background glow and logos fast.",
  thumb: postThumb07,
  hero: postThumb07,
},
{
  slug: "event",
  title: "Eventia",
  titleEs: "Eventia",
  tags: ["Events", "Tickets", "Schedule"],
  desc: "Agenda, speakers, ticket tiers. Swap hero art and colors; keep CTA anchored for conversions.",
  descEs: "Agenda, speakers, ticket tiers. Swap hero art and colors; keep CTA anchored for conversions.",
  thumb: postThumb10,
  hero: postThumb10,
},
{
  slug: "conference",
  title: "SummitSpace",
  titleEs: "SummitSpace",
  tags: ["Conference", "Sponsors", "Agenda"],
  desc: "Sponsor grid, schedule, and venue info. Swap cover gradient and imagery per city stop.",
  descEs: "Sponsor grid, schedule, and venue info. Swap cover gradient and imagery per city stop.",
  thumb: postThumb11,
  hero: postThumb11,
},
{
  slug: "nonprofit",
  title: "ImpactNow",
  titleEs: "ImpactNow",
  tags: ["Nonprofit", "Donations", "Stories"],
  desc: "Mission-driven hero, impact stats, and donation CTA. Swap photography for each campaign quickly.",
  descEs: "Mission-driven hero, impact stats, and donation CTA. Swap photography for each campaign quickly.",
  thumb: postThumb13,
  hero: postThumb13,
},
{
  slug: "education",
  title: "EduFlow",
  titleEs: "EduFlow",
  tags: ["Courses", "Enroll", "Content"],
  desc: "Course catalog, instructors, and enrollment funnel. Replace hero and palette to match your school.",
  descEs: "Course catalog, instructors, and enrollment funnel. Replace hero and palette to match your school.",
  thumb: postThumb15,
  hero: postThumb15,
},
{
  slug: "newsletter",
  title: "InboxPro (Newsletter)",
  titleEs: "InboxPro (Newsletter)",
  tags: ["Newsletter", "Lead Gen", "Waitlist"],
  desc: "Lead magnet landing with social proof. Swap hero illustration or drop in your own product shot.",
  descEs: "Lead magnet landing with social proof. Swap hero illustration or drop in your own product shot.",
  thumb: heroImage01,
  hero: heroImage01,
},
{
  slug: "blog",
  title: "Magnetic Blog",
  titleEs: "Magnetic Blog",
  tags: ["Content", "SEO", "Authors"],
  desc: "Feature posts, categories, and author cards. Swap cover images and accent color without breaking layout.",
  descEs: "Feature posts, categories, and author cards. Swap cover images and accent color without breaking layout.",
  thumb: workflow01,
  hero: workflow01,
},
{
  slug: "knowledge",
  title: "HelpHub",
  titleEs: "HelpHub",
  tags: ["Docs", "Support", "Search"],
  desc: "Knowledge base layout with search and categories. Swap hero and brand color; keep typography consistent.",
  descEs: "Knowledge base layout with search and categories. Swap hero and brand color; keep typography consistent.",
  thumb: workflow02,
  hero: workflow02,
},
{
  slug: "faq",
  title: "Answerly (FAQ)",
  titleEs: "Answerly (FAQ)",
  tags: ["Support", "FAQ", "Contact"],
  desc: "Accordion FAQs with contact CTA. Swap gradient and icon set in seconds.",
  descEs: "Accordion FAQs with contact CTA. Swap gradient and icon set in seconds.",
  thumb: workflow03,
  hero: workflow03,
},
{
  slug: "commerce",
  title: "ShopLine (Retail)",
  titleEs: "ShopLine (Retail)",
  tags: ["Retail", "Catalog", "Cart"],
  desc: "Product highlights, bundles, and cart CTA. Swap hero photography and accent to match your brand.",
  descEs: "Product highlights, bundles, and cart CTA. Swap hero photography and accent to match your brand.",
  thumb: carousel01,
  hero: carousel01,
},
{
  slug: "subscriptions",
  title: "SubFlow",
  titleEs: "SubFlow",
  tags: ["Subscriptions", "Plans", "Billing"],
  desc: "Plan grid with toggles, add-on upsells, and testimonials. Swap palette and hero art quickly.",
  descEs: "Plan grid with toggles, add-on upsells, and testimonials. Swap palette and hero art quickly.",
  thumb: carousel02,
  hero: carousel02,
},
{
  slug: "payments",
  title: "PayFlex",
  titleEs: "PayFlex",
  tags: ["Fintech", "Payments", "Security"],
  desc: "Fintech landing with trust badges, feature tabs, and CTA. Swap device mock shots and gradients.",
  descEs: "Fintech landing with trust badges, feature tabs, and CTA. Swap device mock shots and gradients.",
  thumb: carousel03,
  hero: carousel03,
},
{
  slug: "banking",
  title: "NeoBank",
  titleEs: "NeoBank",
  tags: ["Banking", "Cards", "App"],
  desc: "Card hero, rewards highlights, and app preview. Swap card art and brand color in minutes.",
  descEs: "Card hero, rewards highlights, and app preview. Swap card art and brand color in minutes.",
  thumb: featuresImage,
  hero: featuresImage,
},
{
  slug: "light-saas",
  title: "BrightOps",
  titleEs: "BrightOps",
  tags: ["SaaS", "Automation", "Teams"],
  desc: "Operational tooling with feature tabs and logos. Swap screenshots and CTA text fast.",
  descEs: "Operational tooling with feature tabs and logos. Swap screenshots and CTA text fast.",
  thumb: worldmapImage,
  hero: worldmapImage,
},
{
  slug: "crm",
  title: "ClientLoop (CRM)",
  titleEs: "ClientLoop (CRM)",
  tags: ["CRM", "Pipelines", "Integrations"],
  desc: "Pipeline stages, integration badges, and demo booking. Swap gradient and icons easily.",
  descEs: "Pipeline stages, integration badges, and demo booking. Swap gradient and icons easily.",
  thumb: teamMosaic01,
  hero: teamMosaic01,
},
{
  slug: "video",
  title: "StreamHub",
  titleEs: "StreamHub",
  tags: ["Video", "Courses", "Media"],
  desc: "Video-first layout with episodes and subscribe CTA. Swap cover frame and accent colors quickly.",
  descEs: "Video-first layout with episodes and subscribe CTA. Swap cover frame and accent colors quickly.",
  thumb: teamMosaic02,
  hero: teamMosaic02,
},
{
  slug: "webinar",
  title: "WebinarOne",
  titleEs: "WebinarOne",
  tags: ["Webinar", "Registration", "Reminders"],
  desc: "Webinar signup with schedule, speakers, and reminders. Swap hero art and button copy.",
  descEs: "Webinar signup with schedule, speakers, and reminders. Swap hero art and button copy.",
  thumb: postThumb01,
  hero: postThumb01,
},
{
  slug: "how-it-works",
  title: "FlowSteps",
  titleEs: "FlowSteps",
  tags: ["How it works", "Process", "Explainer"],
  desc: "Step-by-step explainer with visuals and CTA. Swap photos and color accents per product.",
  descEs: "Step-by-step explainer with visuals and CTA. Swap photos and color accents per product.",
  thumb: postThumb02,
  hero: postThumb02,
},
{
  slug: "video-service",
  title: "VidService",
  titleEs: "VidService",
  tags: ["Services", "Video", "Booking"],
  desc: "Video production landing with package tiers and booking. Replace reel cover and palette instantly.",
  descEs: "Video production landing with package tiers and booking. Replace reel cover and palette instantly.",
  thumb: postThumb04,
  hero: postThumb04,
},
{
  slug: "features",
  title: "FeatureGrid",
  titleEs: "FeatureGrid",
  tags: ["Product", "Features", "CTA"],
  desc: "Feature tiles with iconography and CTA. Swap background glow and icons.",
  descEs: "Feature tiles with iconography and CTA. Swap background glow and icons.",
  thumb: postThumb07,
  hero: postThumb07,
},
{
  slug: "projects",
  title: "ProjectHub",
  titleEs: "ProjectHub",
  tags: ["Projects", "Cards", "Kanban"],
  desc: "Project snapshots with CTA to sign up. Swap imagery and keep CTA pinned.",
  descEs: "Project snapshots with CTA to sign up. Swap imagery and keep CTA pinned.",
  thumb: postThumb10,
  hero: postThumb10,
},
{
  slug: "notifications",
  title: "NotifyMe",
  titleEs: "NotifyMe",
  tags: ["Notifications", "API", "Product"],
  desc: "Notification platform landing with API callouts. Swap screenshot and brand color.",
  descEs: "Notification platform landing with API callouts. Swap screenshot and brand color.",
  thumb: postThumb11,
  hero: postThumb11,
},
{
  slug: "freelance",
  title: "IndiePro",
  titleEs: "IndiePro",
  tags: ["Freelance", "Bookings", "Portfolio"],
  desc: "Freelancer landing with packages and booking. Replace workspace photo and accent color.",
  descEs: "Freelancer landing with packages and booking. Replace workspace photo and accent color.",
  thumb: postThumb13,
  hero: postThumb13,
},
{
  slug: "it-services",
  title: "SecureIT",
  titleEs: "SecureIT",
  tags: ["IT", "Security", "Consulting"],
  desc: "IT services with security highlights and consult CTA. Swap hero and brand palette quickly.",
  descEs: "IT services with security highlights and consult CTA. Swap hero and brand palette quickly.",
  thumb: postThumb15,
  hero: postThumb15,
},
{
  slug: "newsletter-pro",
  title: "Inbox Elite",
  titleEs: "Inbox Elite",
  tags: ["Newsletter", "Lead Gen", "Templates"],
  desc: "Newsletter growth page with opt-in, social proof, and stats. Swap device mock and gradient.",
  descEs: "Newsletter growth page with opt-in, social proof, and stats. Swap device mock and gradient.",
  thumb: heroImage01,
  hero: heroImage01,
},
{
  slug: "app-showcase",
  title: "AppShow",
  titleEs: "AppShow",
  tags: ["App", "Showcase", "Downloads"],
  desc: "App showcase with platform badges and feature highlights. Swap screenshots and CTA copy easily.",
  descEs: "App showcase with platform badges and feature highlights. Swap screenshots and CTA copy easily.",
  thumb: workflow01,
  hero: workflow01,
},
];

export function getTemplateBySlug(slug: string) { return templates.find((t) => t.slug === slug); }
